# Generated by Django 4.1.4 on 2023-01-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Create'), (1, 'Paid'), (2, 'On way'), (3, 'Delivered'), (4, 'Waiting')], default=0),
        ),
    ]
